/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    colors: {
      transparent: "transparent",
      primary: "rgb(var(--color-primary) / <alpha-value>)",
      "primary-alt1": "rgb(var(--color-primary-alt1) / <alpha-value>)",
      "primary-alt2": "rgb(var(--color-primary-alt2) / <alpha-value>)",
      "primary-alt3": "rgb(var(--color-primary-alt3) / <alpha-value>)",
      secondary: "rgb(var(--color-secondary) / <alpha-value>)",
      "secondary-alt1": "rgb(var(--color-secondary-alt1) / <alpha-value>)",
      "secondary-alt2": "rgb(var(--color-secondary-alt2) / <alpha-value>)",
      "secondary-alt3": "rgb(var(--color-secondary-alt3) / <alpha-value>)",
      neutral: "rgb(var(--color-neutral) / <alpha-value>)",
      "neutral-alt1": "rgb(var(--color-neutral-alt1) / <alpha-value>)",
      "neutral-alt2": "rgb(var(--color-neutral-alt2) / <alpha-value>)",
      "neutral-alt3": "rgb(var(--color-neutral-alt3) / <alpha-value>)",
      danger: "rgb(var(--color-danger) / <alpha-value>)",
      "danger-alt1": "rgb(var(--color-danger-alt1) / <alpha-value>)",
      "danger-alt2": "rgb(var(--color-danger-alt2) / <alpha-value>)",
      "danger-alt3": "rgb(var(--color-danger-alt3) / <alpha-value>)",
      background: "rgb(var(--color-background) / <alpha-value>)",
      "background-alt": "rgb(var(--color-background-alt) / <alpha-value>)",
      font: "rgb(var(--color-font) / <alpha-value>)",
      "font-invert": "rgb(var(--color-font-invert) / <alpha-value>)",
    },
    spacing: {
      02: "2px",
      04: "4px",
      08: "8px",
      16: "16px",
      24: "24px",
      32: "32px",
      40: "40px",
      48: "48px",
      64: "64px",
      80: "80px",
      96: "96px",
      112: "112px",
      128: "128px"
    },
  },
  plugins: [],
}
