/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    colors: {
      transparent: "transparent",
      primary: "rgb(var(--color-primary) / <alpha-value>)",
      "primary-dark": "rgb(var(--color-primary-dark) / <alpha-value>)",
      "primary-darker": "rgb(var(--color-primary-darker) / <alpha-value>)",
      "primary-light": "rgb(var(--color-primary-light) / <alpha-value>)",
      "primary-lighter": "rgb(var(--color-primary-lighter) / <alpha-value>)",
      secondary: "rgb(var(--color-secondary) / <alpha-value>)",
      "secondary-dark": "rgb(var(--color-secondary-dark) / <alpha-value>)",
      "secondary-darker": "rgb(var(--color-secondary-darker) / <alpha-value>)",
      "secondary-light": "rgb(var(--color-secondary-light) / <alpha-value>)",
      "secondary-lighter": "rgb(var(--color-secondary-lighter) / <alpha-value>)",
      neutral: "rgb(var(--color-neutral) / <alpha-value>)",
      "neutral-dark": "rgb(var(--color-neutral-dark) / <alpha-value>)",
      "neutral-darker": "rgb(var(--color-neutral-darker) / <alpha-value>)",
      "neutral-light": "rgb(var(--color-neutral-light) / <alpha-value>)",
      "neutral-lighter": "rgb(var(--color-neutral-lighter) / <alpha-value>)",
      background: "rgb(var(--color-background) / <alpha-value>)",
      font: "rgb(var(--color-font) / <alpha-value>)",
      "font-invert": "rgb(var(--color-font-invert) / <alpha-value>)",
    },
    spacing: {
      02: "2px",
      04: "4px",
      08: "8px",
      16: "16px",
      24: "24px",
      32: "32px",
      40: "40px",
      48: "48px",
      64: "64px",
      80: "80px",
      96: "96px",
    },
  },
  plugins: [],
}
